### 統計台北市youbike, 各行政區的統計資料

In [4]:
import requests
import pandas as pd
from pydantic import BaseModel, Field, RootModel


youbike_url = 'https://tcgbusfs.blob.core.windows.net/dotapp/youbike/v2/youbike_immediate.json'
res = requests.get(youbike_url)

if res.status_code == 200:
    print('下載成功')
else:
    print('下載失敗')

下載成功

In [6]:
class Site(BaseModel):
    區域: str = Field(alias='sarea')
    總數: int = Field(alias='total')
    可借: int = Field(alias='available_rent_bikes')
    可還: int = Field(alias='available_return_bikes')

class YouBike(RootModel):
    root: list[Site]
    
data: YouBike = YouBike.model_validate_json(res.text)
all_sites: list[dict] = data.model_dump()

In [7]:
df_sites = pd.DataFrame(all_sites)
df_sites

          區域  總數  可借  可還
0        大安區  28  22   6
1        大安區  21  20   1
2        大安區  16  10   6
3        大安區  11  10   1
4        大安區  16   7   9
...      ...  ..  ..  ..
1424  臺大公館校區  30   2  27
1425  臺大公館校區  20   5  15
1426  臺大公館校區  24   1  23
1427  臺大公館校區  40   3  37
1428  臺大公館校區  18   6  12

[1429 rows x 4 columns]

In [12]:
df_sites.groupby(by='區域')[['總數', '可借', '可還']].sum()

          總數    可借    可還
區域
中山區     3819  1556  2214
中正區     3195  1113  2022
信義區     3324  1048  2170
內湖區     3481  1305  2136
北投區     2464   967  1461
南港區     2317  1021  1272
士林區     2923  1077  1745
大同區     1629   617   996
大安區     4975  2227  2617
文山區     2203   862  1335
松山區     2343   911  1395
臺大公館校區  1437   592   831
萬華區     2032   826  1169