In [1]:
import requests
import pandas as pd
from pydantic import BaseModel, Field, RootModel
from datetime import datetime

try:
    youbike_url = 'https://tcgbusfs.blob.core.windows.net/dotapp/youbike/v2/youbike_immediate.json'
    res = requests.get(youbike_url)
    res.raise_for_status()
except Exception as e:
    print(e)
else:
    print('下載成功')

下載成功

In [2]:
class Site(BaseModel):
    區域: str = Field(alias='sarea')
    總數: int = Field(alias='total')
    可借: int = Field(alias='available_rent_bikes')
    可還: int = Field(alias='available_return_bikes')
    時間: datetime = Field(alias='mday')

class YouBike(RootModel):
    root: list[Site]
    
data: YouBike = YouBike.model_validate_json(res.text)
all_sites: list[dict] = data.model_dump()

In [5]:
df_sites = pd.DataFrame(all_sites)
df_sites

          區域  總數  可借  可還                  時間
0        大安區  28   6  22 2024-07-01 19:24:19
1        大安區  21  14   7 2024-07-01 19:22:53
2        大安區  16  10   6 2024-07-01 19:24:20
3        大安區  11   4   7 2024-07-01 19:24:19
4        大安區  16   4  12 2024-07-01 19:24:19
...      ...  ..  ..  ..                 ...
1424  臺大公館校區  30   0  29 2024-07-01 19:19:15
1425  臺大公館校區  20   1  19 2024-07-01 19:21:15
1426  臺大公館校區  24  10  13 2024-07-01 19:21:21
1427  臺大公館校區  40  23   8 2024-07-01 19:24:20
1428  臺大公館校區  18   1  17 2024-07-01 19:02:20

[1429 rows x 5 columns]

In [3]:
df_sites = pd.DataFrame(all_sites)
df_sites.groupby(by='區域')[['總數', '可借', '可還']].sum()

          總數    可借    可還
區域
中山區     3819  1635  2165
中正區     3209  1495  1685
信義區     3331  1374  1870
內湖區     3499  1467  1997
北投區     2472  1003  1442
南港區     2317  1141  1156
士林區     2937  1094  1785
大同區     1629   647   973
大安區     4987  2202  2708
文山區     2203   888  1312
松山區     2343   896  1417
臺大公館校區  1437   476   918
萬華區     2057  1061   975